name: Actualizar Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: write

    steps:
      - name: Generar animación
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: yarijlopez
          github_token: ${{ github.token }}
          games: pacman

      - name: Guardar animación
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
